apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  labels:
    app.kubernetes.io/name: py-wallet
    app.kubernetes.io/part-of: py-wallet
    app.kubernetes.io/environment: dev
spec:
  redirectScheme:
    scheme: https
    permanent: true